targetConfigs:
- name: fetchit
  url: http://github.com/containers/fetchit
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    destinationDirectory: /tmp/ft
    schedule: "*/1 * * * *"
  branch: main
