volume: raw-volume # this needs to match the volume name passed to the podman run command
targets:
- name: harpoon
  url: https://github.com/redhat-et/harpoon
  raw:
    targetPath: examples/raw
    schedule: "*/1 * * * *"
    pullImage: true
  branch: main
