targetConfigs:
- url: https://github.com/containers/fetchit
  branch: main
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    glob: "hello.txt"
    destinationDirectory: /tmp
    schedule: "*/1 * * * *"
  raw:
  - name: raw-ex
    targetPath: examples/raw
    schedule: "*/1 * * * *"
